---

- name: Update hostname
  shell: hostname {{ sync_server_hostname }}

- name: Update /etc/hostname
  copy:
    content: "{{ sync_server_hostname }}\n"
    dest: /etc/hostname

- name: Update /etc/hosts
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
    mode: 0644

- name: Add sync group
  group:
    name: "{{ sync_server_group }}"
    state: present

- name: Add sync user
  user:
    create_home: yes
    group: "{{ sync_server_group }}"
    home: "/home/{{ sync_server_user }}"
    user: "{{ sync_server_user }}"
    state: present

- name: Create sync directory
  file:
    path: "{{ sync_server_dir }}"
    state: directory
    owner: "{{ sync_server_user }}"
    mode: 0775
    group: "{{ sync_server_group }}"

- name: Add fstab entry for external USB drive
  when: sync_server_external_drive_enabled
  lineinfile:
    path: /etc/fstab
    regexp: '\# EXTERNAL DRIVE$'
    line: "{{ sync_server_external_partition }} {{ sync_server_dir }} {{ sync_server_external_file_system }} noexec,user,sync,rw,nofail 0 0 # EXTERNAL DRIVE"
    state: present
