---

- name: Install SyncThing APT keys
  shell: curl -s https://syncthing.net/release-key.txt | apt-key add -
  # Having trouble w/ this on a Ubuntu 14.04 virtual machine:
  # apt_key:
  #   url: https://syncthing.net/release-key.txt
  #   state: present

- name: Add SyncThing stable channel
  lineinfile:
    create: yes
    dest: /etc/apt/sources.list.d/syncthing.list
    regexp: ^deb.*
    line: deb https://apt.syncthing.net/ syncthing stable
    state: present

- name: Update APT after adding SyncThing channel
  shell: apt-get update
  # Having trouble w/ this on a Ubuntu 14.04 virtual machine:
  # apt: update_cache=yes cache_valid_time=0

- name: Install SyncThing
  apt: name=syncthing state=latest
