---

- name: Install SyncThing APT keys
  apt_key:
    url: https://syncthing.net/release-key.txt
    state: present

- name: Add SyncThing stable channel
  lineinfile:
    create: yes
    dest: /etc/apt/sources.list.d/syncthing.list
    regexp: ^deb.*
    line: deb https://apt.syncthing.net/ syncthing stable
    state: present

- name: Update APT after adding SyncThing channel
  apt: update_cache=yes cache_valid_time=3600

- name: Install SyncThing
  apt: name=syncthing state=latest
