---

- include: "install.yml"
  become: yes
  become_user: root

- include: "configure.yml"
  when: sync_server_service
  become: yes
  become_user: root

- include: "ecrypt.yml"
  when: sync_server_service
  become: yes
  become_user: root
  when: sync_server_ecrypt_enabled
